<template>
<main id="todo" class="add-padding--medium">
    <h2 class="row row--center-xs col-xs-10 col-md-5 add-padding-bottom--small">Tell me what tasks need to be done:</h2>

    <form
    class="row row--center-xs form add-padding-bottom--small"
    @submit.prevent="addTodo"
    >
        <div class="col-xs-7 col-md-5">
            <input 
                v-model="newTodoContent"
                class="form__input" 
                type="text" 
                placeholder="Add a To-Do"
            >
        </div>
        <div class="col-xs-1 col-md-1">
            <button
            :disabled="!newTodoContent"
            class="button">
            Add
            </button>
        </div>
        
    </form>


    <div
    v-for="todo in todos"
    class="row row--center-xs"
    :class="{ 'card__success' : todo.done}"
    >
        <div class="card col-xs-10 col-md-8">
            <div 
                class="card__content"
                :class="{'card__text-success card__line-through' : todo.done}"
            >
              <p> {{todo.content}} </p> 

            </div>
            <div class="">
                <button 
                @click="toggleDone(todo.id)"
                class="button"
                :class="todo.done ? 'button__success' : 'button__undone'"
                >
                &check; 
                </button>
                <button 
                @click="deleteTodo(todo.id)"
                class="button button__delete">
                &cross; 
                </button>
            </div>
        </div>
    </div>
</main>

</template>

<script setup>



/*
  imports
*/

import { ref, onMounted } from 'vue';
import { collection, onSnapshot, 
        addDoc, doc, deleteDoc, updateDoc, 
        query, where, 
        orderBy} from "firebase/firestore";
import { getAuth } from "firebase/auth";
import { db } from '@/firebase';


/*
get current user
*/

const auth = getAuth();
const user = auth.currentUser;    


/*
count todos
*/
// const successTodo = collection(db, "todos");
// console.log(successTodo);


/*
  firebase refs
*/

const todosCollectionRef = collection(db, "todos");


const getUserTodoQuery = query(todosCollectionRef, where("userId", "==", user.uid ), orderBy("date", "desc")) // return only data generated by signedin user id




/*
  todos
*/

const todos = ref([
  // {
  //   id: 'id1',
  //   content: 'buy apples',
  //   done: false
  // },
  // {
  //   id: 'id2',
  //   content: 'eat my apples',
  //   done: true
  // }
])


/*
  get todos
*/

onMounted(() => {

  onSnapshot(getUserTodoQuery, (querySnapshot) => {
    const fbTodos = [];

    querySnapshot.forEach((doc) => {
      const todo = {
        id: doc.id, 
        content: doc.data().content,
        done: doc.data().done
        
      }
      
      fbTodos.push(todo)
    });
    todos.value = fbTodos
  },(err) => {console.log(err)});
})




/*
  add todo
*/
const newTodoContent = ref('')


const addTodo = () => {
    
  addDoc(todosCollectionRef, {
    content: newTodoContent.value, //generate todo content
    userId: user.uid, 
    done: false,    
    date: Date.now()
});
  newTodoContent.value = '' // clear input field
}


/*
  delete todo
*/

const deleteTodo = id => {
  deleteDoc(doc(todosCollectionRef, id));
}


/*
  toggle done
*/

const toggleDone = id => {
  const index = todos.value.findIndex(todo => todo.id === id)

  updateDoc(doc(todosCollectionRef, id), {
    done: !todos.value[index].done
  });

}



</script>

<style lang="scss">
   @import "src/assets/styles/master.scss";
</style>